addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 9bcaa114-e93e-4f21-9ab0-170fb6ae0e7d
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 360 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_cache:
- rm -rf $HOME/.m2/repository/org/keycloak
before_install: []
before_script:
- export MAVEN_SKIP_RC=true
branches: ''
cache:
  directories:
  - $HOME/.m2
  - $HOME/.m2
env:
  global:
  - MAVEN_SKIP_RC=true
  - MAVEN_OPTS="-Xms512m -Xmx2048m"
install:
- travis_wait 60 mvn install -Pdistribution -DskipTests=true -B -V -q
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=9bcaa114-e93e-4f21-9ab0-170fb6ae0e7d
script:
- mvn test -B
sudo: false
# Modified by Insights Service at 2016-11-09 18:26:16.762087
